# Generated by Django 4.2.7 on 2025-10-01 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            nombre='Productos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_nombre='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('descripcion', models.TextField(blank=True)),
                ('cantidad', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['nombre'],
            },
        ),
        migrations.DeleteModel(
            nombre='Product',
        ),
    ]
